apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  labels:
    app: docker-k8s-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: kamenskyvo/hello-app
          ports:
            - containerPort: 8080